source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MWPhotoBrowser_Example' do
    #pod "MWPhotoBrowser", :path => "../"
  pod 'MWPhotoBrowser', :podspec =>'https://raw.githubusercontent.com/shenguanjiejie/MWPhotoBrowser/master/MWPhotoBrowser.podspec'
end

target 'MWPhotoBrowser_Tests' do
    #pod "MWPhotoBrowser", :path => "../"
  pod 'MWPhotoBrowser', :podspec =>'https://raw.githubusercontent.com/shenguanjiejie/MWPhotoBrowser/master/MWPhotoBrowser.podspec'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
